fifth_project/fifth_project/urls.py
from django.contrib import admin
from django.urls import include, path
from my_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('', views.index, name='index'),
]

fifth_project/my_app/urls.py
from django.urls import path
from . import views


app_name = 'my_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),

]

fifth_project/my_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

fifth_project/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):

    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

fifth_project/my_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def index(request):
    return render(request, 'my_app/index.html')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False )
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,
                  'my_app/registration.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse('Account not active')

        else:
            print('Someone tried to login and failed')
            return HttpResponse('Invalid login details supplied!')

    else:
        return render(request, 'my_app/login.html', {})

fifth_project/my_app/templates/my_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous">
</head>
<body>
  <nav class="nav">
    <a class="nav-link" href="{% url 'index' %}">Home</a>
    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
    <a class="nav-link" href="{% url 'my_app:register' %}">Register</a>

    {% if user.is_authenticated %}
    <a class="nav-link" href="{% url 'my_app:user_logout' %}">Logout</a>
    {% else %}
    <a class="nav-link" href="{% url 'my_app:user_login' %}">Login</a>
    {% endif %}

  </nav>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>


</body>
</html>

fifth_project/my_app/templates/my_app/index.html
{% extends "my_app/base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Django Project Five</h1>
</div>
{% endblock %}

fifth_project/my_app/templates/my_app/login.html
{% extends "my_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please Login</h1>
  <form action="{% url 'my_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">

  </form>
</div>

{% endblock %}

fifth_project/my_app/templates/my_app/registration.html
{% extends "my_app/base.html" %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registering!</h1>
  {% else %}
    <h1>Register here!</h1>
    <h2>Fill out the form:</h2>

  <form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input type="submit" name="" value="Registration">
  </form>
  {% endif %}
</div>
{% endblock %}