cbv_project/cbv_project/urls.py
from django.contrib import admin
from django.urls import include, path
from my_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('my_app/', include('my_app.urls', namespace='my_app')),
]

cbv_project/my_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
    path('', views.SchoolListView.as_view(), name='list'),
]

cbv_project/my_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

cbv_project/my_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView
from . import models


# Create your views here.
class IndexView(TemplateView):
    template_name = 'my_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['inject'] = "Basic Injection!"
        return context


class SchoolListView(ListView):
    # If you don't pass in this attribute,
    # Django will auto create a context name
    # for you with object_list!
    # Default would be 'school_list'

    # Example of making your own:
    # context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model = models.School
    template_name = 'my_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ("name", "principal", "location")
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ("name", "principal")
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")


class CBView(View):

    def get(self, request):
        return HttpResponse('Class Based Views are Cool!')

cbv_project/my_app/templates/my_app/index.html
{% extends "my_app/my_app_base.html" %}

  {% block body_block %}
    <h1>Welcome to the index page!</h1>
    <h2>Here is your injected content: {{ inject }}</h2>
  {% endblock %}

cbv_project/my_app/templates/my_app/my_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
      {% block title_block %}

      {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous">

</head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Create School</a></li>
        </ul>
    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
          crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"
          integrity="sha256-JAW99MJVpJBGcbzEuXk4Az05s/XyDdBomFqNlM3ic+I="
          crossorigin="anonymous"></script>

</html>

cbv_project/my_app/templates/my_app/school_confirm_delete.html
{% extends "my_app/my_app_base.html" %}

{% block body_block %}
<h1>Delete {{school.name }}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a href="{% url 'basic_app:detail' pk=school.pk%} ">Cancel</a>

</form>

{% endblock %}

cbv_project/my_app/templates/my_app/school_detail.html
{% extends "my_app/my_app_base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Id_num: {{school_details.id}}</p>
    <p>Name: {{school_details.name}}</p>
    <p>Principal: {{school_details.principal}}</p>
    <p>Location: {{school_details.location}}</p>
    <h3>Students:</h3>

      {% for student in school_details.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
      {% endfor %}

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>

  </div>

{% endblock %}

cbv_project/my_app/templates/my_app/school_form.html
{% extends "my_app/my_app_base.html" %}

{% block body_block %}
<h1>
  {% if not form.instance.pk %}
  Create School
  {% else %}
  Update School
  {% endif %}
</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class='btn btn-primary' value="Submit">

  </form>


{% endblock %}

cbv_project/my_app/templates/my_app/school_list.html
{% extends "my_app/my_app_base.html" %}

{% block body_block %}
  <div class="jumbotron">

    <h1>Welcome to the List of Schools Page!</h1>
      <ol>
        {% for school in school_list %}
          <h2><li><a href="{{school.id}}/">{{school.name}} </a></li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}