fourth_project/fourth_project/urls.py
from django.contrib import admin
from django.urls import include, path
from my_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
    path('', views.index, name='index'),
]

fourth_project/my_app/urls.py
from django.urls import path
from . import views


app_name = 'my_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),

]

fourth_project/my_app/models.py
from django.db import models

# Create your models here.

fourth_project/my_app/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    content_dict = {'text': 'hello world',
                    'number': 100}
    return render(request, 'my_app/index.html', content_dict)


def other(request):
    return render(request, 'my_app/other.html')


def relative(request):
    return render(request, 'my_app/relative.html')

fourth_project/my_app/templates/my_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
</head>
<body>
  <nav class="nav">
    <a class="nav-link" href="{% url 'index' %}">Home</a>
    <a class="nav-link" href="{% url 'my_app:other' %}">Other</a>
    <a class="nav-link" href="{% url 'my_app:relative' %}">Relative</a>
    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
  </nav>

  <div class="container">
    {% block body_block %}
    {% endblock %}
  </div>

</body>
</html>

fourth_project/my_app/templates/my_app/index.html
<!DOCTYPE html>
{% extends "my_app/base.html" %}
  {% block body_block %}
  <h1>Welcome to the home page.</h1>
  <h1>{{ text|upper }}</h1>
  <h1>{{ text|cut:'hello' }}</h1>
  <h1>{{ number|add:'99' }}</h1>
  {% endblock %}

fourth_project/my_app/templates/my_app/other.html
<!DOCTYPE html>
{% extends "my_app/base.html" %}
  {% block body_block %}
  <h1>Welcome to the other page.</h1>
  {% endblock %}

fourth_project/my_app/templates/my_app/relative.html
<!DOCTYPE html>
{% extends "my_app/base.html" %}
  {% block body_block %}
  <h1>Welcome to the relative page.</h1>
  {% endblock %}